const products = [
    {
      imageLink: "https://example.com/product1.jpg",
      category: "Electronics",
      title: "Product 1",
      description: "This is a description of product 1.",
      price: 19.99,
    },
    {
      imageLink: "https://example.com/product2.png",
      category: "Clothing",
      title: "Product 2",
      description: "This is a description of product 2.",
      price: 24.99,
    },
    {
        imageLink: "https://example.com/product2.png",
        category: "Clothing",
        title: "Product 2",
        description: "This is a description of product 2.",
        price: 24.99,
      },
      {
        imageLink: "https://example.com/product2.png",
        category: "Clothing",
        title: "Product 2",
        description: "This is a description of product 2.",
        price: 24.99,
      },
      {
        imageLink: "https://example.com/product2.png",
        category: "Clothing",
        title: "Product 2",
        description: "This is a description of product 2.",
        price: 24.99,
      },
      {
        imageLink: "https://example.com/product2.png",
        category: "Clothing",
        title: "Product 2",
        description: "This is a description of product 2.",
        price: 24.99,
      },
      {
        imageLink: "https://example.com/product2.png",
        category: "Clothing",
        title: "Product 2",
        description: "This is a description of product 2.",
        price: 24.99,
      },
      {
        imageLink: "https://example.com/product2.png",
        category: "Clothing",
        title: "Product 2",
        description: "This is a description of product 2.",
        price: 24.99,
      },
      {
        imageLink: "https://example.com/product2.png",
        category: "Clothing",
        title: "Product 2",
        description: "This is a description of product 2.",
        price: 24.99,
      },
      {
        imageLink: "https://example.com/product2.png",
        category: "Clothing",
        title: "Product 2",
        description: "This is a description of product 2.",
        price: 24.99,
      },
  ];